### PR TITLE
Ziyi bc tidal

### PR DESCRIPTION
**Pull request by tzuyilu**
- Modified shiftMyData.m under 'DSM/Derived_Variables':
   (1) deleted the line of the 'run_std_dev'
   (2) added memo about timestamp shift issue

- DSM_FirstStage.ini: added 3 new flags ('flag_B4INSTAL', 'flags_PRI_1_1_1', 'flags_NDVI_1_1_1')

- DSM_SecondStage.ini: Deleted redundant contents
   (1) deleted line of the 'del_sp_seg' in water measurements
   (2) used 'shiftMyData.m' and 'rmNoise.m' to make the 'Evaluate' sections look more concise
   (3) removed 'rmNoise.m' mentioned in pull request #23 

- RBM_FirstStage.ini: 
   (1) corrected a variable name (MET_HMP_RH_4m_Avg)
   (2) added a new flag ('flag_B4INSTAL')

- RBM_SecondStage.ini: Deleted redundant contents:  removed 'rmNoise.m' mentioned in pull request #23

### CODE REVIEW

**Review by znesic — COMMENTED** [review]
I removed rmNoise in one of the previous updates. Your branch seems to want to put it back.
I am also not sure about TS_1 variable and why it still needs ind_delete and does not use a flag.
There is too much use of run_std_dev function. If the data going into SecondStage was already cleaned using this function, there is no need to run it again after calc_avg_trace is applied. Two noise-free clean traces should always produce a noise-free trace (at least, that's my theory :-)).

**Comment by tzuyilu** [comment]
Hi Zoran,
For TS_1_*_1 variables, it will be a good idea to create a flag for them, and I will create one. Just because this flag will be used once, so I put it as an individual line in 2nd stage ini-file. 
In addition, I would like to discuss the usage of 'run_std_dev' with you. I use this function to remove the spikes that can't be identified in the first stage. Those spikes might fall within reasonable ranges but look like sudden jumps in the series. That's why I think they should not stay. So I think we should use this function (but I should put it before the 'calc_avg_trace' actually) in 2nd stage. What do you think?

**Comment by June-Skeeter** [comment]
@tzuyilu yes, the run_std_dev should go before calc_avg_trace if it will be used.  But we'll want to be mindful of which variables it's being applied too.  These are things we should probably discuss collectively so we use the same implementation for all ini files/sites

**Comment by tzuyilu** [comment]
@June-Skeeter  That makes sense to keep consistent across ini-files/sites. We can discuss which variables should be applied at the upcoming meeting. Thanks!

**Comment by tzuyilu** [comment]
Hi @znesic, 
I just edited ini files according to our previous discussions. Here is the updated summary of my edits:

Modified shiftMyData.m under 'DSM/Derived_Variables':
     (1) deleted the line of the 'run_std_dev'
     (2) added memo about timestamp shift issue

DSM_FirstStage.ini: 
     (1) added 3 new flags ('flag_B4INSTAL', 'flags_PRI_1_1_1', 'flags_NDVI_1_1_1')
     (2) added RBM_SW_OUT_1_1_1/RBM_LW_OUT_1_1_1/RBM_NETRAD_1_1_1 (for DSM LWout correction)

DSM_SecondStage.ini: Deleted redundant contents
     (1) deleted line of the 'del_sp_seg' in water measurements
     (2) fixed Biomet lag issue by 'shiftMyData.m' 
     (3) adjusted the order of run_std_dev/calc_avg_trace functions
     (4) removed 'rmNoise.m' mentioned in pull request Ziyi bc tidal #23

RBM_FirstStage.ini:
     (1) corrected a variable name (MET_HMP_RH_4m_Avg)
     (2) added a new flag ('flag_B4INSTAL', 'flag_TS_1')
     (3) changed minMax of spikes_hf_2/5/6/7/8 from [0,0.1] to [0,100]

RBM_SecondStage.ini: 
     (1) Adjusted the order of run_std_dev/calc_avg_trace functions
     (2) removed 'rmNoise.m' mentioned in pull request Ziyi bc tidal #23

**Review by znesic — APPROVED** [review]

**Pull request merged**
